services:
  geth:
    image: ethereum/client-go:v1.10.25
    container_name: alba_eth
    command: >
      --networkid 15
      --http --http.addr 0.0.0.0 --http.port 8545 --http.api "eth,web3,net,personal"
      --mine --miner.etherbase "0x7d9f4d000dccA3B2CC3c77049A7AA1a2Ce6ceCfC" --miner.gasprice 0
      --nodiscover --allow-insecure-unlock
      --ipcdisable
      --verbosity 3
      --metrics --pprof --pprof.addr 0.0.0.0 --pprof.port 6060
      --rinkeby
    ports:
      - "8545:8545"
      - "30303:30303"
      - "6060:6060"
    volumes:
      - ./data:/root/.ethereum

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - geth
  
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus